name: GameBox
author: Nikl
main: me.nikl.gamebox.GameBox
version: 1.5.5
website: nikl.me
softdepend: [Vault, PlaceholderAPI]

name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

commands:
  gamebox:
    description: show the main gui
    usage: /gamebox
    aliases: [games, gb]
  gameboxadmin:
    description: admin commands
    usage: /gameboxadmin
    aliases: [gbadmin, gba]

permissions:
  gamebox.*:
    description: Gives all permissions
    children:
      gamebox.use: true
      gamebox.play.*: true
      gamebox.gamegui.*: true
      gamebox.info: true
      gamebox.help: true
      gamebox.shop: true
      gamebox.admin: true
  gamebox.admin:
    description: Gives permission to use admin commands
    default: op
  gamebox.use:
    description: Allows the player to use /gamebox and the hub item
    default: true
  gamebox.shop:
    description: Allows the player to open the shop from the main menu
    default: true
  gamebox.play.*:
    default: true
    description: Allows the player to play all games
  gamebox.gamegui.*:
    default: true
    description: Allows to open all game guis
  gamebox.info:
    default: true
    description: Allows the usage of the subcommand info
  gamebox.help:
    default: true
    description: Allows the usage of the subcommand help or ?
