name: GameBox
author: Nikl
main: me.nikl.gamebox.GameBox
version: 1.0.2
website: nikl.me
softdepend: [Vault]

commands:
  gamebox:
    description: show the main gui
    usage: /gamebox
    aliases: [games, gb]

permissions:
  gamebox.*:
    description: Gives all permissions
    children:
      gamebox.admin: true
  gamebox.admin:
    description: Gives all permissions
    default: op
    children:
      gamebox.use: true
      gamebox.play.*: true
      gamebox.gamegui.*: true
      gamebox.info: true
      gamebox.help: true
  gamebox.use:
    description: Allows the player to open the main guis (use /gamebox)
    default: true
  gamebox.play.*:
    default: true
    description: Allows the player to play all games
  gamebox.gamegui.*:
    default: true
    description: Allows to open all game guis
  gamebox.info:
    default: op
    description: Allows the usage of the subcommand info
  gamebox.help:
    default: true
    description: Allows the usage of the subcommand help or ?
