name: GameBox
author: Nikl
main: me.nikl.gamebox.Main
version: 1.0

commands:
  gamebox:
    description: show the main gui
    usage: /gamebox
    aliases: [games, gb]

permissions:
  gamebox.*:
    description: Gives all permissions
    children:
      gamebox.admin: true
  gamebox.admin:
    description: Gives all permissions
    default: op
    children:
      gamebox.reload: true
      gamebox.use: true
      gamebox.play.*: true
  gamebox.use:
    description: Allows the player to open the main guis (use /gamebox)
    default: true
  gamebox.play.*:
    description: Allows the player to play all games
    default: true
  gamebox.gamegui.*:
    default: true
    description: Allows to open all game guis
