name: GameBox
author: Nikl
main: me.nikl.gamebox.Main
version: 1.0

commands:
  gamebox:
    description: show the main gui
    usage: /gamebox
    aliases: [games, gb]

permissions:
  gamebox.*:
    description: Gives all permissions
    children:
      gamebox.admin: true
  gamebox.admin:
    description: Gives all permissions
    default: op
    children:
      gamebox.reload: true
      gamebox.use: true
      gamebox.*.play: true
      gamebox.*.bypass: true
  gamebox.use:
    description: Allows the player to open the main gui (use /gamebox)
    default: true
  gamebox.*.play:
    description: Allows the player to play all games
    default: true
    children:
      gamebox.gemcrush.play: true
      gamebox.battleship.play: true
      gamebox.minesweeper.play: true
  gamebox.gemcrush.play:
    description: Allows to play GemCrush
  gamebox.battleship.play:
    description: Allows to play Battleship
  gamebox.minesweeper.play:
    description: Allows to play Minesweeper
  gamebox.*.bypass:
    description: Allows the player to bypass all costs (also no pay!)
    children:
      gamebox.gemcrush.play: true
      gamebox.battleship.play: true
      gamebox.minesweeper.play: true
  gamebox.gemcrush.bypass:
    description: Allows to bypass GemCrush costs (also no pay!)
  gamebox.battleship.bypass:
    description: Allows to bypass Battleship costs (also no pay!)
  gamebox.minesweeper.bypass:
    description: Allows to bypass Minesweeper costs (also no pay!)

