# ----------------------------------------------------------------------------#
#                                                                             #
#                              Tetris config                                  #
#                                                                             #
# ----------------------------------------------------------------------------#



# requires vault and an economy plugin
economy:
  enabled: false
  cost: 0
  reward: 0