# ----------------------------------------------------------------------------#
#                                                                             #
#                              Match It config                                #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "default"

rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "95:11"
    # display name of the button
    displayName: "&3Match It"
    # lore of the button
    lore:
    - ""
    - "&1Memory game;"
    - "&1Find all pairs."
  gameButtons:
    game1:
      materialData: "95:11"
      displayName: "&aMatch It"
      lore:
      - ""
      - "&1Memory game;"
      - "&1Find all pairs."
      slot: 20
      cost: 0
      # if true the best score of this button is saved
      saveStats: true


  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    game1:
      materialData: "95:13"
      displayName: "&6Match It &c&lTop list"
      slot: 24
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '        &6Match It &rTop List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the players' best time
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Time:&1 %time%'

items:
  '1':
    # material data of the item
    matData: "98"
    # optional custom display name
    displayName: "&1Stone Bricks"
    # optional custom lore
    lore:
    - ""
    - "Old and with many cracks"
  '2':
    # material data of the item
    matData: "100"
    # optional custom display name
    displayName: "&1Red Mushroom Block"
  '3':
    # material data of the item
    matData: "101"
    # optional custom display name
    displayName: "&1Iron Bars"
  '4':
    # material data of the item
    matData: "103"
    # optional custom display name
    displayName: "&1Melon"
  '5':
    # material data of the item
    matData: "106"
    # optional custom display name
    displayName: "&1Vines"


