# ----------------------------------------------------------------------------#
#                                                                             #
#                              Match It config                                #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "default"

rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "95:11"
    # display name of the button
    displayName: "&3Match It"
    # lore of the button
    lore:
    - ""
    - "&1Memory game;"
    - "&1Find all pairs."
  gameButtons:
    small:
      materialData: "95:11"
      displayName: "&aMatch It"
      lore:
      - ""
      - "&1Memory game;"
      - "&1Find all pairs."
      slot: 11
      cost: 0
      size: "small"
      # if true the best score of this button is saved
      saveStats: true
    medium:
      materialData: "95:11"
      displayName: "&aMatch It"
      lore:
      - ""
      - "&1Memory game;"
      - "&1Find all pairs."
      slot: 20
      cost: 0
      size: "medium"
      # if true the best score of this button is saved
      saveStats: true
    big:
      materialData: "95:11"
      displayName: "&aMatch It"
      lore:
      - ""
      - "&1Memory game;"
      - "&1Find all pairs."
      slot: 29
      cost: 0
      size: "big"
      # if true the best score of this button is saved
      saveStats: true



  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    medium:
      materialData: "95:13"
      displayName: "&6Match It &c&lTop list"
      slot: 24
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '        &6Match It &rTop List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the players' best time
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Time:&1 %time%'

items:
  '1':
    # material data of the item
    materialData: "98"
    # optional custom display name
    displayName: "&1Stone Bricks"
    # optional custom lore
    lore:
    - ""
    - "Old and with many cracks"
  '2':
    # material data of the item
    materialData: "100"
    # optional custom display name
    displayName: "&1Red Mushroom Block"
  '3':
    # material data of the item
    materialData: "101"
    # optional custom display name
    displayName: "&1Iron Bars"
  '4':
    # material data of the item
    materialData: "103"
    # optional custom display name
    displayName: "&1Melon"
  '5':
    # material data of the item
    materialData: "106"
    # optional custom display name
    displayName: "&1Vines"
  '6':
    # material data of the item
    materialData: "387"
    # optional custom display name
    displayName: "&1Book"
    lore:
    - ""
    - "You should read that!"
    - "     - your teacher"
  '7':
    # material data of the item
    materialData: "diamond"
    # optional custom display name
    displayName: "&1Diamond"
  '8':
    # material data of the item
    materialData: "emerald"
    # optional custom display name
    displayName: "&1Emerald"
  '9':
    # material data of the item
    materialData: "341"
    # optional custom display name
    displayName: "&1Slime"
  '10':
    # material data of the item
    materialData: "egg"
    # optional custom display name
    displayName: "&1Egg"
  '11':
    # material data of the item
    materialData: "302"
    # optional custom display name
    displayName: "&1Ancient helmet"
    lore:
    - ""
    - "Maybe Ceasar wore it?..."
  '12':
    # material data of the item
    materialData: "357"
    # optional custom display name
    displayName: "&1Cookie"
    lore:
    - ""
    - "Grandmas cookies are the best!"
  '13':
    # material data of the item
    materialData: "352"
    # optional custom display name
    displayName: "&1A bone..."
  '14':
    # material data of the item
    materialData: "358"
    # optional custom display name
    displayName: "&1Map"
    lore:
    - ""
    - "I wonder where it leads to..."


