name: GameBox
author: Nikl
main: me.nikl.gamebox.GameBox
version: 2.0.0-BETA
website: nikl.me
softdepend: [Vault, PlaceholderAPI, CalendarEvents]

permissions:
  gamebox.*:
    description: Gives all permissions
    children:
      gamebox.use: true
      gamebox.play.*: true
      gamebox.gamegui.*: true
      gamebox.info: true
      gamebox.help: true
      gamebox.shop: true
      gamebox.admin.*: true
  gamebox.admin.*:
    description: Gives permission to use all admin commands
    default: false
    children:
      gamebox.admin.database: true
      gamebox.admin.language: true
      gamebox.admin.reload: true
      gamebox.admin.token: true
  gamebox.admin.database:
    description: Player can manipulate the database via commands
    default: false
  gamebox.admin.language:
    description: Player can get language information via commands
    default: false
  gamebox.admin.reload:
    description: Player can reload the plugin via command
    default: false
  gamebox.admin.token:
    description: Player can manipulate token balances via commands
    default: false
  gamebox.use:
    description: Allows the player to use /gamebox and the hub item
    default: true
  gamebox.shop:
    description: Allows the player to open the shop from the main menu
    default: true
  gamebox.play.*:
    default: true
    description: Allows the player to play all games
  gamebox.gamegui.*:
    default: true
    description: Allows to open all game guis
  gamebox.info:
    default: true
    description: Allows the usage of the info command
  gamebox.help:
    default: true
    description: Allows the usage of the help command
